- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Create new AMI
      ec2_ami:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: "{{ INSTANCE_AMI_ID }}"
        name: "{{ INSTANCE_AMI_NAME }}"
        #wait: yes
        state: absent
