- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: remove old key
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: ansible
        state: absent
    - name: create a new ec2 keypair
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: ansible
      register: ansible
    - debug:
        var: ansible
    - name: write new private key to file locally
      lineinfile:
        create: yes
        path: /root/ansible/ansible.pem
        line: "{{ ansible.key.private_key }}"
        mode: 0600
