- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Gather snapshot facts
      ec2_snapshot_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
    - name: Create Volume Snapshot
      ec2_snapshot:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
      #  instance_id: i-0211e650e99b4c54d
       # device_name: /dev/sdf
        snapshot_id: snap-029d22478a3aa1e4a
        state: absent
        description: "On demand volume backup."
